name: Testing github actions

on: 
  push:
    branches:
      - master

      jobs: 
        deploy: 
          runs-on: ubuntu-latest

          steps: 
            - name: Checkout code
              uses: action/checkout@v2

            - name: Deploy to shared hosting
              uses: Samkland/FTP-Deploy-Action@4.3.0
              with: 
                server: ${{ secrets.FTP_SERVER }}
                username: ${{ secrets.FTP_USERNAME}}
                password: ${{ secrets.FTP_PASSWORD}}
                local-dir: ./
                remote-dir: /public_html/fixit.pisco.name.ng